#font

font_family		Iosevka Nerd Font Complete
bold_font		Iosevka Bold Nerd Font Complete
italic_font		Iosevka Italic Nerd Font Complete
bold_italic_font	Iosevka Bold Italic Nerd Font Complete

font_size 12.0

# sound

enable_audio_bell 	no

# padding

window_padding_width 5

# colortheme

foreground		#d8dee9
background		#2e3440
selection_foreground	#000000
selection_background	#fffacd
url_color		#0087bd
cursor			#81a1c1

# black
color0			#3b4252
color8			#4c566a

# red
color1			#bf616a
color9			#bf616a

# green
color2			#a3be8c
color10			#a3be8c

# yellow
color3			#ebcb8b
color11			#ebcb8b

# blue
color4			#81a1c1
color12			#81a1c1

# magenta
color5			#b48ead
color13			#b48ead

# cyan
color6			#88c0d0
color14			#8fbcbb

# white
color7			#e5e9f0
color15			#eceff4
