#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

nitrogen --restore &

bspc config border_width         3
bspc config window_gap          25
bspc config top_padding         40

bspc config split_ratio          0.52

theme="macchiato"

if [ "$theme" == "latte" ]; then
    normal_border_color="#dce0e8"
    focused_border_color="#1e66f5"
else
    normal_border_color="#181926"
    focused_border_color="#8aadf4"
fi

bspc config normal_border_color "$normal_border_color"
bspc config focused_border_color "$focused_border_color"

bspc rule -a Emacs state=tiled

bash "$HOME"/dev/scripts/setup_monitors.sh
bash "$HOME"/.config/polybar/launch.sh
