#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

nitrogen --restore &

bspc config border_width        2
bspc config window_gap          25
bspc config top_padding         40

bspc config split_ratio          0.52

COLORFILE="$HOME/.colortheme"

if [[ -f "$COLORFILE" ]]; then
    theme=$(cat "$COLORFILE")
else
    theme="nano-light"
fi

if [ "$theme" == "nano-light" ]; then
    normal_border_color="#37474F"
    focused_border_color="#FFAB91"
else
    normal_border_color="#ECEFF4"
    focused_border_color="#D08770"
fi

bspc config normal_border_color "$normal_border_color"
bspc config focused_border_color "$focused_border_color"

bspc rule -a Emacs state=tiled
bspc rule -a kitty-launcher state=floating

bash "$HOME"/dev/scripts/setup_monitors.sh
bash "$HOME"/.config/polybar/launch.sh
