#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

setxkbmap ch &
nitrogen --restore
$HOME/.config/polybar/launch.sh

bspc monitor -d www dev sys doc chat mus vid

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding         30

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
